apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka-broker
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-broker
  template:
    metadata:
      labels:
        io.kompose.service: kafka-broker
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      containers:
        - env:
            - name: CLUSTER_ID
              value: MkU3OEVBNTcwNTJENDM2Qk
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:9092
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka-broker:9093
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
          image: confluentinc/cp-kafka:7.5.0
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-data
            - mountPath: /etc/kafka/secrets
              name: kafka-secrets
      volumes:
        - name: kafka-data
          emptyDir: {}
        - name: kafka-secrets
          emptyDir: {}
