apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    io.kompose.service: kibana
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.name: "kibana"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
