apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/retina/Documents/Village/Aeroport-Clean/docker-compose.elk.yml -o /Users/retina/Documents/Village/Aeroport-Clean/k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /Users/retina/Documents/Village/Aeroport-Clean/docker-compose.elk.yml -o /Users/retina/Documents/Village/Aeroport-Clean/k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: -Xms256m -Xmx256m
          image: docker.elastic.co/logstash/logstash:7.17.18
          name: logstash
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "768Mi"
          volumeMounts:
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: logstash-cm0
              subPath: logstash.yml
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-cm1
              subPath: logstash.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: logstash.yml
                path: logstash.yml
            name: logstash-cm0
          name: logstash-cm0
        - configMap:
            items:
              - key: logstash.conf
                path: logstash.conf
            name: logstash-cm1
          name: logstash-cm1
