apiVersion: v1
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }

    filter {
      if [logger_name] {
        mutate {
          add_field => { "service" => "%{app_name}" }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "aeroport-logs-%{+YYYY.MM.dd}"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: logstash
  name: logstash-cm1
