apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: postgres-reservations
  name: postgres-reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-reservations
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: postgres-reservations
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: reservations_db
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
          image: postgres:15
          name: postgres-reservations
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-reservations-data
      restartPolicy: Always
      volumes:
        - name: postgres-reservations-data
          persistentVolumeClaim:
            claimName: postgres-reservations-data
