apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: service-auth
  name: service-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: service-auth
    spec:
      containers:
        - env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-auth:5432/auth_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
          image: moboks/aeroport-service-auth:v1
          name: service-auth
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
