apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: service-reservations
  name: service-reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-reservations
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: service-reservations
    spec:
      containers:
        - env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-reservations:5432/reservations_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:9092
            - name: JAVA_OPTS
              value: -Xmx256m
          image: moboks/aeroport-service-reservations:v1
          imagePullPolicy: Never
          name: service-reservations
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            requests:
              memory: "384Mi"
            limits:
              memory: "512Mi"
      restartPolicy: Always
