apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: service-notifications
  name: service-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-notifications
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: service-notifications
    spec:
      containers:
        - env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-notifications:5432/notifications_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:9092
          image: moboks/aeroport-service-notifications:v1
          name: service-notifications
          ports:
            - containerPort: 8084
              protocol: TCP
      restartPolicy: Always
